---
- name: Run systemctl restart nginx_exporter
  listen: systemctl restart nginx_exporter
  become: true
  ansible.builtin.systemd:
    name: nginx_exporter
    state: restarted
    daemon_reload: true
